---
# defaults file for ssh_server

ssh_server_listen_port: 22
ssh_server_listen_protocol: 2

ssh_server_login_grace_time: 2m
ssh_server_permit_root_login: "prohibit-password" # prohibit-password - yes - no
ssh_server_strict_modes: "yes"
ssh_server_max_auth_tries: 6
ssh_server_max_sessions: 10
ssh_server_pubkey_authentication: "yes"
ssh_server_password_authentication: "no" # yes or no
ssh_server_permit_empty_passwords: "no"

ssh_server_use_PAM: "yes"

ssh_server_allow_users:
  - myself

ssh_server_allow_tcp_forwarding: "yes"

ssh_server_x11forwarding: "yes"

ssh_server_permit_TTY: "yes"
ssh_server_print_motd: "no"
ssh_server_print_last_log: "yes"
ssh_server_TCP_keep_alive: "yes"
ssh_server_client_alive_interval: 0
ssh_server_client_alive_count_max: 3
ssh_server_max_startups: "10:30:100"
